name: ticeo
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.1.0
  flutter_screenutil: ^5.0.0
  animate_do: ^2.0.0
  animations: ^2.0.11
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_rating_bar: ^4.0.1
  email_validator: ^2.0.1
  salomon_bottom_bar: ^3.3.2
  provider: ^6.0.0
  audioplayers: ^1.0.0 #^5.2.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  google_fonts: ^4.0.4
  percent_indicator: ^4.2.3
  url_launcher: ^6.0.20
  android_intent_plus: ^3.0.0
  google_maps_flutter: ^2.2.5
  webview_flutter: ^4.0.6
  loading_animation_widget: ^1.2.1
  flutter_chat_ui: ^1.6.15
  file_picker: ^8.0.0
  http: ^0.13.5
  open_filex: ^4.0.1
  bubble: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/iconApp.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/iconApp.png"


flutter:
  uses-material-design: true
  assets:
      - assets/sounds/select_tap.wav
      - assets/images/deffault_profil.jpg
      - assets/sounds/assistance_bienvenue.aac
      - assets/sounds/del.mp3
      - assets/sounds/add.mp3
      - assets/images/
      - assets/logo/
      - assets/icons/
      - assets/design_course/
      - assets/fitness_app/
      - assets/hotel/
      - assets/introduction_animation/
      - assets/messages.json
  fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400
        - family: DotGothic
          fonts:
              - asset: assets/fonts/DotGothic16-Regular.ttf
                weight: 400
        - family: Jersey
          fonts:
              - asset: assets/fonts/Jersey10-Regular.ttf
                weight: 400
        - family: Gilroy
          fonts:
              - asset: assets/fonts/GILROY-EXTRABOLD.OTF
              - asset: assets/fonts/GILROY-LIGHT.OTF
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Light.ttf
                weight: 300
              - asset: assets/fonts/Poppins-Medium.ttf
                weight: 500
              - asset: assets/fonts/Poppins-Regular.ttf
                weight: 600
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 700
              - asset: assets/fonts/Poppins-ExtraBold.ttf
                weight: 800
              
